# Generated by Django 5.1.15 on 2026-09-27 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_event_community_voting_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communityvote",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="voteauditlog",
            options={"ordering": ["-timestamp", "-id"]},
        ),
        migrations.AddField(
            model_name="communitycomment",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communitycomment",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communitycomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="communityvote",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Abuse heuristics raised when the vote was cast",
            ),
        ),
        migrations.AddField(
            model_name="communityvote",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communityvote",
            name="is_void",
            field=models.BooleanField(
                default=False, help_text="Voided by an organizer; excluded from tallies"
            ),
        ),
        migrations.AddField(
            model_name="communityvote",
            name="void_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="evaluationauditlog",
            name="dwell_seconds",
            field=models.FloatField(
                blank=True,
                help_text="Seconds between first opening the project and scoring it",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evaluationauditlog",
            name="flags",
            field=models.JSONField(
                blank=True, default=list, help_text="e.g. LOO_OUTLIER, RAPID_SUBMISSION"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="allow_self_vote",
            field=models.BooleanField(
                default=False,
                help_text="If False, team members cannot vote for their own team's project",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="judges_per_project",
            field=models.PositiveIntegerField(
                default=3, help_text="Target number of judge reviews per project (K)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="results_published",
            field=models.BooleanField(
                default=False,
                help_text="Judging leaderboard is hidden from everyone but the organizer until published",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="votes_per_user",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Maximum community votes a single user may cast in this event (0 = unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="voting_eligibility",
            field=models.CharField(
                choices=[
                    ("any", "Any signed-in user"),
                    ("registered", "Only users registered on a team in this event"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="judgeassignment",
            name="opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First time the judge opened this project (server clock)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voteauditlog",
            name="entry_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="voteauditlog",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_audit_logs",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="voteauditlog",
            name="flagged",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="voteauditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="voteauditlog",
            name="prev_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="event",
            name="show_community_voting_results",
            field=models.BooleanField(
                default=False,
                help_text="If False, vote counts are hidden from the public until voting closes",
            ),
        ),
        migrations.AlterField(
            model_name="voteauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("VOTED", "Voted"),
                    ("UNVOTED", "Vote removed"),
                    ("VOTE_REJECTED", "Vote rejected"),
                    ("VOTE_VOIDED", "Vote voided by organizer"),
                    ("COMMENTED", "Comment posted"),
                    ("COMMENT_EDITED", "Comment edited"),
                    ("COMMENT_REMOVED", "Comment removed"),
                    ("COMMENT_REJECTED", "Comment rejected"),
                    ("SETTINGS_CHANGED", "Voting settings changed"),
                ],
                default="VOTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voteauditlog",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vote_audit_logs",
                to="events.projectsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="voteauditlog",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
