# Generated by Django 5.1.15 on 2026-09-29 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_webhookendpoint_webhookdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('winner', 'Winner'), ('judge', 'Judge'), ('organizer', 'Organizer')], default='participant', max_length=30)),
                ('title', models.CharField(help_text='e.g. Certificate of Participation, 1st Place Winner', max_length=200)),
                ('award_title', models.CharField(blank=True, default='', max_length=200)),
                ('certificate_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
                ('recipient_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.team')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('event', 'recipient_user', 'role', 'award_title')},
            },
        ),
        migrations.CreateModel(
            name='JudgeParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('evaluations_count', models.PositiveIntegerField(default=0)),
                ('rubrics_scored_count', models.PositiveIntegerField(default=0)),
                ('first_evaluation_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluation_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_digest', models.CharField(blank=True, default='', max_length=64)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_records', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_participation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'judge')},
            },
        ),
    ]
