# Generated by Django 5.1.15 on 2026-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_certificate_judgeparticipationrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="revocation_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="signed_payload",
            field=models.JSONField(
                blank=True, default=dict, help_text="Exact claims that were signed"
            ),
        ),
        migrations.AddField(
            model_name="judgeparticipationrecord",
            name="average_score_given",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgeparticipationrecord",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgeparticipationrecord",
            name="signed_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
