from django.urls import path
from .views import (
    AdminEventManageView,
    AdminAllTeamsView,
    AdminTeamManageView,
    AdminTeamMemberManageView,
    AdminAllSubmissionsView,
    AdminSubmissionManageView,
    AdminEventJudgeManageView,
    EventListCreateView,
    EventDetailView,
    CreateTeamView,
    JoinTeamView,
    LeaveTeamView,
    SubmitProjectView,
    MySubmissionView,
    EventSubmissionsListView,
    PublicGalleryView,
    EventRubricsManageView,
    SubmitProjectEvaluationView,
    EventLeaderboardView,
    AdminAssignJudgesView,
    AdminJudgingProgressView,
    AdminExportLeaderboardCSVView,
    AdminExportRubricsCSVView,
    AdminExportFeedbackCSVView,
    AdminExportSubmissionsCSVView,
    AdminExportAssignmentsCSVView,
    AdminExportEvaluationAuditCSVView,
    PublishResultsView,
    EventWebhooksView,
    EventWebhookDetailView,
    EventWebhookDeliveriesView,
    WebhookRedeliverView,
    WebhookEventTypesView,
    EventWebhookTestView,
    TeamInviteLookupView,
    GenerateCertificatesView,
    EventCertificatesListView,
    MyCertificatesListView,
    PublicCertificateDetailView,
    DownloadCertificateSVGView,
    PublicJudgeRecordVerifyView,
    MyJudgeRecordView,
    BulkEventExportView,
    BulkEventImportView,
    BulkTeamImportCSVView,
)
from .community import (
    CommunityVoteView,
    VotingStatusView,
    CommunityResultsView,
    CommentListCreateView,
    CommentDetailView,
    CommunityAuditView,
    CommunityAuditVerifyView,
    CommunityVotesAdminView,
    VoidVoteView,
    ExportCommunityVotesCSVView,
    ExportCommunityAuditCSVView,
)

urlpatterns = [
    path('', EventListCreateView.as_view(), name='event_list_create'),
    path('<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('<int:pk>/teams/create/', CreateTeamView.as_view(), name='team_create'),
    path('<int:pk>/teams/join/', JoinTeamView.as_view(), name='team_join'),
    path('<int:pk>/teams/lookup/', TeamInviteLookupView.as_view(), name='team_invite_lookup'),
    path('<int:pk>/teams/leave/', LeaveTeamView.as_view(), name='team_leave'),
    path('<int:pk>/submit/', SubmitProjectView.as_view(), name='project_submit'),
    path('<int:pk>/my-submission/', MySubmissionView.as_view(), name='my_submission'),
    path('<int:pk>/submissions/', EventSubmissionsListView.as_view(), name='event_submissions'),
    path('<int:pk>/gallery/', PublicGalleryView.as_view(), name='event_gallery'),
    path('<int:event_pk>/submissions/<int:sub_pk>/vote/', CommunityVoteView.as_view(), name='submission_vote'),
    path('<int:pk>/rubrics/', EventRubricsManageView.as_view(), name='event_rubrics'),
    path('<int:pk>/rubrics/<int:rubric_pk>/', EventRubricsManageView.as_view(), name='event_rubric_detail'),
    path('<int:event_pk>/submissions/<int:sub_pk>/evaluate/', SubmitProjectEvaluationView.as_view(), name='submission_evaluate'),
    path('<int:pk>/leaderboard/', EventLeaderboardView.as_view(), name='event_leaderboard'),
    path('<int:pk>/admin/assign-judges/', AdminAssignJudgesView.as_view(), name='admin_assign_judges'),
    path('<int:pk>/admin/judging-progress/', AdminJudgingProgressView.as_view(), name='admin_judging_progress'),
    path('<int:pk>/admin/export/leaderboard-csv/', AdminExportLeaderboardCSVView.as_view(), name='admin_export_leaderboard_csv'),
    path('<int:pk>/admin/export/rubrics-csv/', AdminExportRubricsCSVView.as_view(), name='admin_export_rubrics_csv'),
    path('<int:pk>/admin/export/rubric-breakdown-csv/', AdminExportRubricsCSVView.as_view(), name='admin_export_rubric_breakdown_csv'),
    path('<int:pk>/admin/export/feedback-csv/', AdminExportFeedbackCSVView.as_view(), name='admin_export_feedback_csv'),
    path('<int:pk>/admin/export/submissions-csv/', AdminExportSubmissionsCSVView.as_view(), name='admin_export_submissions_csv'),
    path('<int:pk>/admin/export/assignments-csv/', AdminExportAssignmentsCSVView.as_view(), name='admin_export_assignments_csv'),
    path('<int:pk>/admin/export/evaluation-audit-csv/', AdminExportEvaluationAuditCSVView.as_view(), name='admin_export_evaluation_audit_csv'),
    path('<int:pk>/admin/publish-results/', PublishResultsView.as_view(), name='admin_publish_results'),

    # T3 - community voting, comments, audit
    path('<int:pk>/voting/', VotingStatusView.as_view(), name='voting_status'),
    path('<int:pk>/community-results/', CommunityResultsView.as_view(), name='community_results'),
    path('<int:event_pk>/submissions/<int:sub_pk>/comments/', CommentListCreateView.as_view(), name='submission_comments'),
    path('<int:event_pk>/comments/<int:comment_pk>/', CommentDetailView.as_view(), name='comment_detail'),
    path('<int:pk>/admin/community-audit/', CommunityAuditView.as_view(), name='admin_community_audit'),
    path('<int:pk>/admin/community-audit/verify/', CommunityAuditVerifyView.as_view(), name='admin_community_audit_verify'),
    path('<int:pk>/admin/community-votes/', CommunityVotesAdminView.as_view(), name='admin_community_votes'),
    path('<int:pk>/admin/community-votes/<int:vote_pk>/void/', VoidVoteView.as_view(), name='admin_void_vote'),
    path('<int:pk>/admin/export/community-votes-csv/', ExportCommunityVotesCSVView.as_view(), name='admin_export_community_votes_csv'),
    path('<int:pk>/admin/export/community-audit-csv/', ExportCommunityAuditCSVView.as_view(), name='admin_export_community_audit_csv'),

    path('admin/events/<int:pk>/', AdminEventManageView.as_view(), name='admin_event_manage'),
    path('admin/events/<int:pk>/judges/', AdminEventJudgeManageView.as_view(), name='admin_event_judge_manage'),
    path('admin/teams/', AdminAllTeamsView.as_view(), name='admin_all_teams'),
    path('admin/teams/<int:pk>/', AdminTeamManageView.as_view(), name='admin_team_manage'),
    path('admin/teams/<int:team_pk>/members/<int:user_pk>/', AdminTeamMemberManageView.as_view(), name='admin_team_member_manage'),
    path('admin/submissions/', AdminAllSubmissionsView.as_view(), name='admin_all_submissions'),
    path('admin/submissions/<int:pk>/', AdminSubmissionManageView.as_view(), name='admin_submission_manage'),

    # T4 - webhooks
    path('<int:pk>/webhooks/', EventWebhooksView.as_view(), name='event_webhooks'),
    path('<int:pk>/webhooks/<int:webhook_pk>/', EventWebhookDetailView.as_view(), name='event_webhook_detail'),
    path('webhook-events/', WebhookEventTypesView.as_view(), name='webhook_event_types'),
    path('<int:pk>/webhooks/<int:webhook_pk>/test/', EventWebhookTestView.as_view(), name='event_webhook_test'),
    path('<int:pk>/webhooks/<int:webhook_pk>/deliveries/', EventWebhookDeliveriesView.as_view(), name='event_webhook_deliveries'),
    path('<int:pk>/webhooks/<int:webhook_pk>/deliveries/<int:delivery_pk>/redeliver/', WebhookRedeliverView.as_view(), name='event_webhook_redeliver'),

    # T4 Stretch - Certificates & Verification
    path('<int:pk>/admin/certificates/generate/', GenerateCertificatesView.as_view(), name='event_certificates_generate'),
    path('<int:pk>/certificates/', EventCertificatesListView.as_view(), name='event_certificates_list'),
    path('<int:pk>/my-certificates/', MyCertificatesListView.as_view(), name='my_certificates_list'),
    path('certificates/<str:code>/', PublicCertificateDetailView.as_view(), name='public_certificate_detail'),
    path('certificates/<str:code>/download/', DownloadCertificateSVGView.as_view(), name='download_certificate_svg'),

    # T4 Stretch - Signed Judge Participation Records
    path('<int:pk>/my-judge-record/', MyJudgeRecordView.as_view(), name='my_judge_record'),
    path('judges/records/<str:record_id>/verify/', PublicJudgeRecordVerifyView.as_view(), name='public_judge_record_verify'),

    # T4 Stretch - Bulk Import & Export (Portability)
    path('<int:pk>/admin/export/bulk-archive/', BulkEventExportView.as_view(), name='admin_export_bulk_archive'),
    path('admin/import/bulk-archive/', BulkEventImportView.as_view(), name='admin_import_bulk_archive'),
    path('<int:pk>/admin/import/teams-csv/', BulkTeamImportCSVView.as_view(), name='admin_import_teams_csv'),
]

